### ISSUE TITLE
REST API Authentication with OAuth or JWT Token

### ISSUE THREAD

**Issue by cleanstartgit** [greenbits/brick#100]
Is there a way to configure the Brick RestProvider to handle authentication with the API endpoint?

As an example, I have a published web API, but it only responds to authorized app requests. To authenticate, our app will need to send a POST to /token with encrypted credentials in body. If validated, the API returns a token good for 4 hours. On all subsequent requests, the app will include this token in the request Header.

I was unable to find any good examples or docs on how to accomplish this. I'm curious to hear if this is possible. or if there are maybe other options for adding security for the REST interface.

**Comment by tshedor** [comment]
@cleanstartgit thanks for using brick.

You should retrieve the token and then store it on the default headers that will be accessed when making subsequent requests:

```dart
import 'package:http/http.dart' as http;

try {
  final authResponse = http.post('/token', headers: myEncryptedCredentials);
  final token = jsonDecode(authReponse.body)['token'];
  MyRepository().remoteProvider.defaultHeaders = { 'Authorization' => 'Token $token', 'Content-Type': 'application/json' }
} catch (e) {

}
```

**Comment by cleanstartgit** [comment]
@tshedor Thank you for the quick response! 

I saw the defaultHeaders field in the docs late last night, but I couldn't figure out how to access/set them. Thank you for the insight.

This is such an amazing app, kudos to you and the team. I will gladly buy you guys pizzas and beer next time I'm out that way!
