### ISSUE TITLE
Question: Best practices for handling Offline/Rest with nested objects

### ISSUE THREAD

**Issue by cleanstartgit** [greenbits/brick#101]
Hi @tshedor , got another question for you.

I'm working with an existing API. I'm dealing with an endpoint that returns a list of Share objects. The attached is an example of the JSON result. Is this supported by Brick, and if so, how would I go about telling the REST provider to parse JSON from the response, and not to perform get() on the /request,  /member,  or /update endpoints?

Side note: I feel like a better solution would be change the API response, such that request_id is returned, then I could let Brick be responsible for hydrating memory or SQL before using REST. Talking to management, that might be an option.

[json.txt](https://github.com/greenbits/brick/files/5598319/json.txt)

**Comment by tshedor** [comment]
Hey @cleanstartgit to ignore specific endpoints, adjust your `endpoint` to return [null or to only target a specific endpoint](https://pub.dev/documentation/brick_rest/latest/rest/RestSerializable/endpoint.html). When you return `null` from `endpoint`, RestProvider does not make the request to your API. 

```dart
@ConnectOfflineFirstWithRest(
  restConfig: RestSerializable(
    fieldRename: FieldRename.snake,
    endpoint: r'''{
      if (query?.action == QueryAction.get) {
        return '/shares';       
      }

      if (query?.action == QueryAction.upset) {
        ....
      }

      return null;
    }''',
  ),
)
```

I would avoid tweaking hydration logic unless you've exhausted all other options.
