### ISSUE TITLE
Delete error: cannot be deleted because it does not exist in the SQLite database.

### ISSUE THREAD

**Issue by polRk** [greenbits/brick#102]
My code
```
  @override
  Future<bool> deleteTask(TaskDto task) {
    return delete<TaskDto>(task);
  }
```

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): TaskDto{id: fee0dd3e-ea4e-4900-a651-06c6d5f5f9ee, createdAt: 2020-11-14 11:23:42.878768Z, updatedAt: 2020-11-14 11:23:42.878769Z} cannot be deleted because it does not exist in the SQLite database.
#0      SqliteProvider.delete (package:brick_sqlite/sqlite.dart:75:7)
<asynchronous suspension>
#1      OfflineFirstRepository.delete (package:brick_offline_first/offline_first.dart:101:46)
#2      OfflineFirstWithRestRepository.delete (package:brick_offline_first/offline_first_with_rest.dart:95:26)
#3      TasksRepositoryIml.deleteTask
#4      _TasksStore.deleteTask
```

But in sqlite the object exists

<img width="419" alt="Screenshot 2020-11-28 at 16 04 56" src="https://user-images.githubusercontent.com/39828645/100516220-76eb0780-3193-11eb-94e8-f661ddf06130.png">

**Comment by tshedor** [comment]
Hey @polRk good to hear from you again. 

Based on the source code where that exception is thrown, I would expect that the `task` you're passing has not had the primary key (`task.primaryKey`) associated to it.

My best guess for why this is happening here starts with the `Dto` in your model name. I assume that `TaskDto` is not the end model and is instead a gobetween for `Task`. Brick's generated adapters **are data transfer objects**. They translate between REST/Sqlite. So a Dart model within your `app/models` directory duplicates this logic and may introduce edge cases like this where your `Task` is sync'd but your `TaskDto` is not.

Second, if you are treating your models as immutable and emulating the `copyWith` method found in many Flutter widgets, be sure to carry `primaryKey`. For example:

```dart
class Task extends OfflineFirstWithRestModel {
  Task({
    this.id,
    this.updatedAt
  });

  Task copyWith({
    String id,
    DateTime updatedAt
  }) {
    return Task(
      id: id ?? this.id,
      updatedAt: updatedAt ?? this.updatedAt
    )..primaryKey = this.primaryKey;
  }
}
```

**Comment by polRk** [comment]
Thank you, @tshedor !
Yes, primaryKey is missing.
```
flutter: existsTask TaskDto{primaryKey: 12, id: fee0dd3e-ea4e-4900-a651-06c6d5f5f9ee}
flutter: FINEST: 2020-11-30 12:31:09.884303: #delete: {"action":4,"providerArgs":{}}
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): TaskDto{primaryKey: null, id: fee0dd3e-ea4e-4900-a651-06c6d5f5f9ee} cannot be deleted because it does not exist in the SQLite database.
```

**Comment by polRk** [comment]
I found an error, the error was in the data encoder/decoder. After encoding, the primary key disappeared.

```dart
final taskDto = taskCodec.encode(task);
```

**Comment by polRk** [comment]
@tshedor Can you explain why I should use instance != null? Because without this, null may come and the application returns an error.

```dart
if (query?.action == QueryAction.delete && instance != null) {
        return "/tasks/${instance.id}";
}
```

**Comment by tshedor** [comment]
@polRk In the future, if the issue is about a new concern, please open a new issue. I'll address this one here this time.

I don't understand the question, as you've answered it. Calling `.id` on `null` will throw an exception, you're right. So we need to ensure that `instance != null`.
