### ISSUE TITLE
Not Seeing Customers

### ISSUE THREAD

**Issue by SubutaDan** [greenbits/brick#103]
I worked through the example by following the tutorial on "Flutter by Example" and so far I have not seen any customers in my Flutter app.  The app builds cleanly (after I remove the pizza import mentioned below), and starts and runs without incident. When it starts I get the "migrating message".  Then some print statements I added tell me that it is inside the migrated==true builder but customerList.data is first null and then becomes an empty list: [].  My server.d console output doesn't show any activity from the app.  The server, however, is responding correctly to others customers requests:

dan@psl64b1:~/repos/kokodoko20191207/Kokodoko - Dec 7$ wget -nv -O - http://localhost:8080/customers
{
  "customers": [
    {
      "id": 1,
      "pizza_ids": [
        1
      ],
      "firstName": "Wallace",
      "lastName": "Wallaceton"
    }
  ]
}2020-12-03 12:44:28 URL:http://localhost:8080/customers [152/152] -> "-" [1]
dan@psl64b1:~/repos/kokodoko20191207/Kokodoko - Dec 7$ 

I can see that the query.action == QueryAction.get case is executed in customer_adapter.g.dart, but I haven't been able to figure out what is happening next.  My guess, for what it's worth, is that Brick is successfully querying SQLite and getting no rows back, but I don't know how to investigate that possibility. Any thoughts on how I can track down the issue?

Thanks.

**Comment by tshedor** [comment]
Hey @SubutaDan , a few things I would do to debug this. 

I think you're right, that there's some cached data it's querying. Brick by default will get fresh data if none exists (`hydrateUnexisting`), so I'm not sure that there are _no_ rows in SQLite, just _empty_ rows.

You can force Brick to always fetch from the API by passing `requireRemote` to the `.get` method. If `requireRemote: true` is in the `.get` call, does your `server.dart` log the request when you boot the app?

**Comment by SubutaDan** [comment]
Hi @tshedor , I started over and I'm not getting data now whether requireRemote is true or false.  A print statement in main reports that  customers is empty.  I can see from another print statement in customer_adapter.g.dart that /customers with no id is being returned from the final case (instance == null).  I added two more print statements to to see whether Rest or SQLite was being used:

```
Future<Customer> fromRest(Map<String, dynamic> input,
      {provider, repository}) async {
    print("in fromRest, provider.baseEndpoint: ${provider.baseEndpoint}");
    await _$CustomerFromRest(input, provider: provider, repository: repository);
  }

Future<Customer> fromSqlite(Map<String, dynamic> input,
      {provider, repository}) async {
    print("in fromSQLite, provider.dbName: ${provider.dbName}");
    await _$CustomerFromSqlite(input,
        provider: provider, repository: repository);
  }
```
and I don't see either of them regardless of which way I set requireRemote.  Does that indicate that neither data source is being queried?

Thanks very much for your patient help.

-Dan

**Comment by SubutaDan** [comment]
Hi @tshedor , I'm getting results in the app now whether or not I set `requireRemote: true`. As near as I can tell, the problem had to do with something being incorrect or out of sync in the SQLite data.  I have been re-initializing the SQLite data store (at least I think I have) by explicitly deleting the app from the emulated phone.  I think I remember reading  about a way to reinitialise the SQLite data store from within the app, presumably to facilitate testing. I can't find that information now.  Can you point me at the doc or remind me how to do it?

Customer first name and customer last name are both null in the results I get in the app.  I can remedy this adding field name annotations:
```
  @Rest(name: 'firstName')
  final String firstName;

  @Rest(name: 'lastName')
  final String lastName;
```
The example code doesn't seem to show these annotations.  When are they required?

Thanks very much for your help.

-Dan

**Comment by tshedor** [comment]
@SubutaDan ahh great catch. I've written a poor API. The member endpoint is camel case while the collection endpoint is snake. I'll open a PR immediately. 

Regarding the SQLite information, do any of these help? 
* [SQLite testing](https://github.com/greenbits/brick/blob/master/packages/brick_sqlite/README.md#testing)
* [Stubbing OfflineFirst endpoints](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/README.md#stubbing-multiple-models)
* [Creating a fresh provider with the repository](https://github.com/greenbits/brick#setup-2)

**Comment by SubutaDan** [comment]
Thanks, @tshedor . -Dan
