### ISSUE TITLE
SqliteProvider.resetDb() doesn't delete bricks HttpJobs table

### ISSUE THREAD

**Issue by polRk** [greenbits/brick#105]
<img width="345" alt="Screenshot 2020-12-11 at 11 42 56" src="https://user-images.githubusercontent.com/39828645/101881818-05a15080-3ba6-11eb-9dc2-4f1e9033173d.png">

**Comment by polRk** [comment]
Apparently brick writes headers to the HttpJobs table, and there the Authorization header has an expired token

**Comment by polRk** [comment]
brick_offline_first-0.1.0/lib/src/offline_queue/offline_request_queue.dart
```
    final request = await client.requestManager.prepareNextRequestToProcess();

   !!!! Request include expired Authorization headers

   await client.send(request);
```

**Comment by tshedor** [comment]
@polRk That's correct. `SqliteProvider` manages SqliteModels from the repository. `HttpJobs` is not part of the logic domain; it only contains generated HTTP requests.

If you want to delete all jobs in the `HttpJobs` table (note that this will be unrecoverable):

```dart
import 'package:brick_offline_first/src/offline_queue/request_sqlite_cache_manager.dart'
    show HTTP_JOBS_PRIMARY_KEY_COLUMN;

final requests = await MyRepository().offlineRequestQueue.client.requestManager.unprocessedRequests();
final requestsToDelete = requests.map((request) {
  return MyRepository().offlineRequestQueue.client.requestManager
    .deleteUnprocessedRequest(request[HTTP_JOBS_PRIMARY_KEY_COLUMN]);
});

await Future.wait(requestsToDelete);
```

**Comment by polRk** [comment]
Thank you, @tshedor !
