### ISSUE TITLE
Best practices for managing server's database schema and objects

### ISSUE THREAD

**Issue by mrmeyers99** [greenbits/brick#114]
The documentation doesn't cover much about implementing the server for the REST endpoints.  I'm wondering if it would be a good idea to somehow share the model and the persistence code between the flutter app and the central rest server that clients are syncing too.  I think I'd have to write a mysql provider for brick since it's not a good idea to run a sqlite database in production, and I'd need to use a repository that doesn't do any remote hydration from another source (since it is the source of truth).

Is this a good idea or would it be better to completely separate my server and client code?

**Comment by tshedor** [comment]
@mrmeyers99 I would use a lot of caution when sharing the same code between server and client, as some data should not be exposed to the client and some client methods would just muddy the server (see ["Provide an all-encompassing solution"](https://github.com/greenbits/brick/issues/106#issuecomment-748658030)). That's not to say the same models could inherit from the same super class, and they could implement any extra bits that are necessary. 

If you're not using Brick against an existing API, I'd also consider writing a modern API that still suits your needs but could be  better than REST. Like protobuf, or websockets, or GraphQL. 

I'd recommend checking out #106 and seeing if that provides any more clarity.

**Comment by mrmeyers99** [comment]
Thanks, that is helpful, I'll follow that PR.
