### ISSUE TITLE
Feedback on the new docs site

### ISSUE THREAD

**Issue by tshedor** [greenbits/brick#130]
Hey @SubutaDan @mrmeyers99 @polRk @cleanstartgit, I've finally put together a documentation website: https://greenbits.github.io/brick/#/  

I'm pinging you because I've previously gone back and forth with each of you on issues that could have likely been resolved with better documentation and clarity. Hopefully this presentation will improve the experience for other users of Brick. Specifically, I'd like to know:

* Is the documentation is easy to navigate?
* Are the pages properly prioritized? 
* Where did you get stuck when you first used Brick? Would you have been able to resolve that problem with this documentation site?
* How did you first come across Brick?
* What is missing?

I'll close this issue in a week, and no hard feelings if you'd rather not respond or have moved on from using Brick.

Also tagging @porfirioribeiro @pkozlovskiy @carlos-labrador since you've been using Brick for a while and will have good insight.

**Comment by polRk** [comment]
I didn't quite understand how to resolve conflicts? 

Where can I specify a function that will say what is the source of truth (item from rest or from local database)?

**Comment by porfirioribeiro** [comment]
Thanks for your effort, the site looks good and helps to have a place with all information well structured!

**Comment by papakay** [comment]
This is really an amazing work. Thank you so much for the great effort and the excellent work you've done.

**Comment by tshedor** [comment]
@polRk Would you mind taking a look at #132 and letting me know if that documentation helps?

@porfirioribeiro @papakay thank you for the kind words, I really appreciate it
