### ISSUE TITLE
Field Level Annotations

### ISSUE THREAD

**Issue by SubutaDan** [greenbits/brick#137]
Hi @tshedor ,

I have puzzled repeatedly over this section of the doc:

_**Annotations**
As providers are ultimately responsible for converting raw data into model data, a description of fields on models is overly generic. Field-level annotations always override class-level annotations/configuration. However, providers should adhere to some standards of annotations:_

After much head scratching here is what I think it means:

_**Annotations**_
_This section discusses Brick's built-in annotations that can be used on model fields._

_Brick's  field level annotations are applied selectively to the providers that process the annotated models. Each type of annotation can be applied to any provider type, and each occurrence of an annotation includes the provider type to which that occurrence applies.  For example, this annotation occurrence :_
```
@Rest(ignore: true)
```
_instructs Rest providers to ignore the annotated field, while this one:_
```
@Sqlite(ignore: true)
```
_tells Sqlite  providers to do the same._

_When a provider is processing a model that includes a field level annotation referring to that type of provider, it is the job of the provider to act on the annotated field in a way that is consistent with the annotation's meaning. Each provider included with Brick processes model fields in accordance with the Brick's built-in field level annotations.  Implementers of new provider types  should ensure that their providers also react appropriately to the field level annotations built into Brick._

  _Some field level annotations control properties that can also be managed using class level annotations or equivalent configurations. In those cases, the field level annotations override the corresponding class level annotations or configuration._

Is that correct?  If not and if you let me know what have I misunderstood, I will update my explanation

Thanks.

-Dan

**Comment by tshedor** [comment]
@SubutaDan thanks for writing this up, I appreciate it. Notes below

> Each type of annotation can be applied to any provider type

Annotations should be bound to a specific provider or a specific repository paradigm. For example, `@Rest` does not affect `@Sqlite` and `@OfflineFirst` does not affect `@Rest` or `@Sqlite`. They should be strictly coupled to their domain. 

By `occurrence` do you mean instance? This will seem very nitpicky, but I want to clarify because it may be a CS concept. I associate occurrence with a time and instance with space; since this doesn't have to do with timing, I'd defer to instance.

> When a provider is processing a model that includes a field level annotation referring to that type of provider, it is the job of the provider to act on the annotated field in a way that is consistent with the annotation's meaning. Each provider included with Brick processes model fields in accordance with the Brick's built-in field level annotations. Implementers of new provider types should ensure that their providers also react appropriately to the field level annotations built into Brick.

Can we tighten up this paragraph to something closer to below? Let me know if this becomes muddied again:

```
When a provider generates a model that includes a field level annotation referring to that provider, it is the job of the provider to interpret the annotated field. All annotations from core Brick providers adhere to the following table; implementers of new provider types should ensure that their annotation adheres to the same base specification. For more, see `FieldSerializable`.
```

**Comment by SubutaDan** [comment]
Thanks, @tshedor . I will try to improve my draft by applying your feedback. -Dan

**Comment by SubutaDan** [comment]
Hi Tim,

At the bottom of this message is a new draft in which I have tried to incorporate your feedback.

-Dan
=====
**Annotations**
This section discusses Brick's built-in annotations that can be used on model fields.

Brick's field level annotations are applied selectively to the providers that process the annotated models. Annotations should be bound to a specific provider or a specific repository paradigm: An annotation labelled "@Rest" affects the @Rest provider but does not affect a Sqlite  provider or an OfflineFirst provider, and an annotation labelled "@OfflineFirst" does not affect a Rest provider or a Sqlite provider. They are strictly coupled to their domains. 

For example, this annotation instance:

```
@Rest(ignore: true)
```
instructs Rest providers to ignore the annotated field, while this one:

```
@Sqlite(ignore: true)
```
tells Sqlite providers to do the same.

When a provider generates a model that includes a field level annotation referring to that provider, it is the job of the provider to interpret the annotated field. All annotations from core Brick providers adhere to the following table; implementers of new provider types should ensure that their annotation adheres to the same base specification. For more, see `FieldSerializable`.


Some field level annotations control properties that can also be managed using class level annotations or equivalent configurations. In those cases, the field level annotations override the corresponding class level annotations or configuration.

**Comment by tshedor** [comment]
@SubutaDan that looks good to me. One more nit is that instead of bolding the annotations they should be wrapped in back-ticks to denote code. For example, instead of "**rest**" it should be `@Rest`.

Do you intend to open a PR with this documentation?

**Comment by tshedor** [comment]
@SubutaDan I'm going to close this due to inactivity; I'd really appreciate a PR with documentation updates around your discovery
