### ISSUE TITLE
Table Not Found

### ISSUE THREAD

**Issue by SubutaDan** [greenbits/brick#138]
Hello,

I am using offline-first-with-rest. My app. has been working well with one model.  I added a second model ('Kokoer') and when I try to execute a query against it I get an exception:
```
E/flutter (  423): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DatabaseException(no such table: Kokoer (code 1): , while compiling: SELECT COUNT(*) FROM `Kokoer`) sql 'SELECT COUNT(*) FROM `Kokoer`' args []}
```

If I remove the attempt to execute the query against the second model type the app again works as expected.

I am initiating queries against both models through the same Repository. I can see that the new table and its columns are referenced in the migration code and in schema.g.dart.  I can also see that build_runner created a  .g.dart and an adapter for the new model type, and I can see that migration is running each time I run the app.

I have tried flushing the app's storage and also uninstalling and reinstalling the app.

Any thoughts on where my mistake might be?

Thank you for your help.

-Dan

**Comment by tshedor** [comment]
@SubutaDan I would expect failures in a couple of obvious places, without knowing the repository code:

In your repository class, when you call super, make sure you're passing migrations from `schema.g.dart`:
`super(migrations: migrations,)`

Make sure you're calling `MyRepository#initialize` in your code before accessing that table and it's `await`ed. And if you've changed the implementation of `initialize`, make sure you invoke `await super.initialize`.

Lastly, make sure running `flutter pub run build_runner build` multiple times without changes to your models does not produce additional migrations. If running that command does, your model definition is most likely off

**Comment by SubutaDan** [comment]
Thanks, @tshedor .  Problem seems to have been caused by my not awaiting the completion of super.initialize before trying to use the new model type.  -Dan
