### ISSUE TITLE
Default authorization header

### ISSUE THREAD

**Issue by Xitaris27** [greenbits/brick#157]
Is there a way to gracefully handle default headers? I have to add an Authorization header to the queries in order to get data from my REST API server and I'd love to not have to explicitly set the header for each query.

Also, it creates an issue when I'm trying to use associations since the queries created in the adapters because they aren't given necessary authorization header. I'd rather not edit the generated files.

I'm new to flutter and mobile dev, so if I'm missing something obvious please let me know

**Comment by tshedor** [comment]
@Xitaris27 thanks for using Brick.

You can set a `defaultHeader` on your [RestProvider](https://github.com/greenbits/brick/blob/master/packages/brick_rest/lib/src/rest_provider.dart#L21). If you're using `OfflineFirstWithRestRepository`, you can do that like so:

```dart
@override
Future<void> initialize() async {
  remoteProvider.defaultHeaders = {'Authorization': '......'};
  await super.initialize();
}
```

It doesn't have to be in `initialize` either: you can call it from your repository: `MyRepository().remoteProvider.defaultHeaders =`.

**Comment by Xitaris27** [comment]
Perfect! Thanks!
