### ISSUE TITLE
Query multiple ids

### ISSUE THREAD

**Issue by Xitaris27** [greenbits/brick#158]
I'd like to be able to query using multiple ids, but I'm not sure how to best build the query.

I tried building a query doing something like this:
...
    List<Where> where = List<Where>();
    for (var id in ids){
      where.add(Or('id').isExactly(id));
    }
    var query = Query(where: where);
    return Repository().get<User>(query: query);
...

is that the best way to handle this case?

**Comment by tshedor** [comment]
@Xitaris27 I forget the name of this, but you can use if and for within Dart iterables. For example:

```dart
final query = Query(where: [
  for (var id in ids) Or('id').isExactly(id),
]);
```

But otherwise, yes, that's how you would build the query.
