### ISSUE TITLE
Duplicate data

### ISSUE THREAD

**Issue by Xitaris27** [greenbits/brick#160]
I'm updating an app that needs REST to be the source of truth to use Brick .

I'm having an issue where, once the sqlite database has been hydrated (assuming I'm using the term correctly), then I'm no longer refreshing the data via the restProvider.

I tried setting alwaysHydrate: true, but this caused me to get duplicate data (instead of updating existing entities).

I also tried setting requireRemote: true, which also resulted in duplicated data.

How should I be configuring my app to get the behavior I want? Do I need to setup custom hydration?

Edit: do I need to be annotating my id field as unique?

**Comment by tshedor** [comment]
@Xitaris27 I would strongly recommend supporting a foreign key to identify your data between your local and remote providers, so to answer your question about annotating your `id` field as `@Sqlite(unique: true)` - yes, you should
