### ISSUE TITLE
Flush the Queue of Pending Operations

### ISSUE THREAD

**Issue by SubutaDan** [greenbits/brick#161]
Hello, I am using OfflineFirstWithRest.  When a user logs out I want to remove any pending REST operations from the internal queue.  Do you have a recommendation for how to do that?  Thanks.  -Dan

**Comment by tshedor** [comment]
@SubutaDan you can do something like this within your repository:

```dart
// find all pending REST ops
final requests = await offlineRequestQueue.client.requestManager.unprocessedRequests();

final requestsToDelete = requests.map((request) {
  // load all requests using the public method `deleteUnprocessedRequest`
  return offlineRequestQueue.client.requestManager.deleteUnprocessedRequest(request[HTTP_JOBS_PRIMARY_KEY_COLUMN]);
});

// run and await all futures at once
await Future.wait(requestsToDelete);
```

**Comment by SubutaDan** [comment]
Thanks, Tim. I will give it a try.

-Dan

On 5 April 2021 06:33:52 BST, Tim Shedor ***@***.***> wrote:
>@SubutaDan you can do something like this within your repository:
>
>```dart
>// find all pending REST ops
>final requests = await
>offlineRequestQueue.client.requestManager.unprocessedRequests();
>
>final requestsToDelete = requests.map((request) {
>// load all requests using the public method `deleteUnprocessedRequest`
>return
>offlineRequestQueue.client.requestManager.deleteUnprocessedRequest(request[HTTP_JOBS_PRIMARY_KEY_COLUMN]);
>});
>
>// run and await all futures at once
>await Future.wait(requestsToDelete);
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenbits/brick/issues/161#issuecomment-813195089

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tshedor** [comment]
Hey @SubutaDan I'm going to close this; let me know if the code didn't work out for you

**Comment by SubutaDan** [comment]
Hi, Tim.  Thanks for getting  back top me about this.  I made the change you suggested and, although I haven't done any focused testing, I also haven't noticed any uploads after the user logs out so I think it is working. -Dan
