### ISSUE TITLE
Force HTTP Method

### ISSUE THREAD

**Issue by Xitaris27** [greenbits/brick#163]
Is it possible to force a specific HTTP method?
I'd like to retrieve some data from my REST server API, but I'd like to make a post request so I can put the query data in a post body.

Is it possible?

**Comment by tshedor** [comment]
@Xitaris27 yep, you can force [a specific HTTP method](https://greenbits.github.io/brick/#/rest/query?id=providerargs) using `providerArgs: { 'request' : 'PUT'}`.

By default, all `upsert` calls in OfflineFirstWithRestRepository submit to the API as POST. All `delete` calls submit as PUT.

If you need to put additional data that the adapter does not generate in your payload, you can use `supplementalTopLevelData` (defined on the same page linked above)

**Comment by tshedor** [comment]
Hey @Xitaris27 going to close this but let me know if you run into another problem.

**Comment by tshedor** [comment]
@Xitaris27 what is the use case where you're using `POST` during a `GET` request?
