### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by Xitaris27** [greenbits/brick#166]
I'm running into an issue where I'm making too many requests - one way I've tried to simplify things is to group requests together and returning all of the info I needed together.

For instance, I have an Order with a an OrderPart, like so, { order: {id: string, ... orderPartIn: {} } all returned in one request from the server. This seems to mostly work the way I want it to by **not** calling .getAssociation() for orderPart when using the restProvider. However, the Sqlite provider insists on calling .getAssociation() if orderPartIn= null. 

How do I tell it to not do this? Especially since the getAssociation method doesn't work properly since it's making incorrect assumptions about how my server API is setup.

PS. is there any documentation on **all** of the possible annotations that Brick accepts? I wasn't able to find a comprehensive list.

**Comment by tshedor** [comment]
@Xitaris27 a few options:
1. Use a specification like `@Rest(ignore: true)` on your field. This would allow you to store `OrderPart` and query it. 
2. Use custom generators like `@Rest(fromGenerator:)` or `@Sqlite(fromGenerator:)`
3. `If OrderPart` is being returned from the server without a dedicated endpoint, you could use an `OfflineFirstSerdes` instead (at the expense of not having SQL querying of `OrderPart` but this may be a worthwhile sacrifice). 

Regarding **all** annotations, there is not a single documentation page with every annotation. Brick is designed to be composed with different providers/use cases, so I would direct you to the Fields section of each provider within the documentation.
