### ISSUE TITLE
Schema issue with latest migration

### ISSUE THREAD

**Issue by Xitaris27** [greenbits/brick#167]
I've been having an issue when running flutter pub run build_runner build when ever I make updates to my models. For some reason, the latest migration is not being included in the schema file and I've been having to manually add the 'part' statement as well as adding it to the migration list.

If I make multiple changes and run the command to generate a migration between each change, it will include the migration for all of my changes except the latest change.

Is this an issue you're aware of? Have other people been having this issue? Can you reproduce it? If this is something we can fix it would save me a lot of time, thanks!

**Comment by tshedor** [comment]
@Xitaris27 Sorry for the delay. I've encountered this and it's something I keep meaning to get to. 

If you run `flutter pub run build_runner build` to generate the migration, run it **again** and the new migration will be added to `schema.g.dart`.

**Comment by tshedor** [comment]
@Xitaris27 I'm going to close this at the end of the day unless you've got any new updates?
