### ISSUE TITLE
Bug: Warning for non-nullable maps

### ISSUE THREAD

**Issue by vandres** [greenbits/brick#187]
When working with non-nullable maps, the generated code throws a warning. The field looks like this: `final Map<String, dynamic> meta;`. The generated code looks like this:

```
 'meta': jsonEncode(instance.meta ?? {}),
```

Since the field is non-nullable, the `??` operation is not necessary.

**Comment by tshedor** [comment]
@vandres thanks for the issue; I've merged in a fix to master and uploaded to pub dev. Please update your `brick_offline_first_with_rest_build` dependency
