### ISSUE TITLE
Work with MemoryCacheProvider 

### ISSUE THREAD

**Issue by kirill09** [greenbits/brick#189]
Hi thanks for the great library.
Working with MemoryCacheProvider found the following code:

```
if (memoryCacheProvider.canFind<_Model>(query)) {
    final results = memoryCacheProvider.get<_Model>(query: query, repository: this);

    return results?.isNotEmpty ?? false;
}

return await sqliteProvider.exists<_Model>(query: query, repository: this);
```
https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/src/offline_first_repository.dart#L116

Why, if we did not find the data in the memoryCacheProvider, do we return false. It seems to me that there should be a request for sqliteProvider.exists?

**Comment by tshedor** [comment]
Hi @kirill09 thanks for the question. 

The thinking behind this decision is the sourcing of the providers. Think of the providers like a ladder - at the lowest, most performant level is Memory, then SQLite, then REST. Or, if you're better with spatial diagrams, [this may be more useful](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/README.md#brick-offline-first). If we can return from the most performant provider, we should. And if the memory provider notifies us that it can source the data given the model and the query, it is immediately considered our source of truth. Returning `false` will also indicate upstream that the memory provider needs to be hydrated.

If you'd rather always access the SQLite provider, I'd recommend overriding the method in your repository:

```dart
@override
Future<bool> exists<_Model extends _RepositoryModel>({
  Query? query,
}) async {
  if (memoryCacheProvider.canFind<_Model>(query)) {
    final results = memoryCacheProvider.get<_Model>(query: query, repository: this);

    if (results?.isNotEmpty ?? false) return true;
  }

  return await sqliteProvider.exists<_Model>(query: query, repository: this);
}
```

**Comment by kirill09** [comment]
Yes, but you are missing the query step in **sqliteProvider**.
If we pass **MemoryCacheProvider([Model, Model])** the following algorithm is executed:
- query for **exists** 
- method **canFind** returns true 
- but there is no data in **memoryCacheProvider**
- go to https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/src/offline_first_repository.dart#L157
- In the hydrate method we query the **remoteProvider**

In this algorithm there is no query to **sqliteProvider**?

If we pass an empty **MemoryCacheProvider()** then everything works as you describe
- a call to the **exists** 
- the **canFind** method returns false
- query the **sqliteProvider**
- .....

**Comment by tshedor** [comment]
@kirill09 I don't understand the flow you're describing. Where I'm getting lost is the difference between "no data" `memoryCacheProvider` and "empty" `memoryCacheProvider`. Do you mean, in the second case, you're not specifying `managedModelTypes`? Annotated method below:

```dart
/// this will return `true` if the [_Model] exists in the `managedModelTypes`. 
/// Let's assume that `canFind` resolves `true`
if (memoryCacheProvider.canFind<_Model>(query)) {
  /// however, when we try to fetch the specific instance, this will return false 
  /// (i.e. a no data `memoryCacheProvider`)
  final results = memoryCacheProvider.get<_Model>(query: query, repository: this);

  /// this control does not exit early from the method. If no specific instance was 
  /// found, or the instance was null, `return true` is never evaluated
  if (results?.isNotEmpty ?? false) return true;
}

/// since there were no results, the `sqliteProvider` is now queried
/// if there is no data in the `sqliteProvider`, `restProvider` will be queried during `hydrate`
return await sqliteProvider.exists<_Model>(query: query, repository: this);
```

**Comment by kirill09** [comment]
The code in the master branch is different from the one you showed.
https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/src/offline_first_repository.dart#L116

master branch:
```return results?.isNotEmpty ?? false;```

you showed:
```if (results?.isNotEmpty ?? false) return true;```

**Comment by tshedor** [comment]
@kirill09 Correct. My comment from 13 days ago and from 17 hours ago were suggestions of how you could override the `exists` method in your repository to get the functionality you want.

**Comment by kirill09** [comment]
@tshedor Thanks. I was wondering why brick has such an implementation

**Comment by tshedor** [comment]
@kirill09 it's because if we can find it in our memory provider, we should be able to, otherwise the memory provider needs to be hydrated. Otherwise the data fetching would constantly skip over memory provider and get the data from the second lowest provider, SQLite.

**Comment by tshedor** [comment]
Hey @kirill09 going to close this one out
