### ISSUE TITLE
Row query

### ISSUE THREAD

**Issue by kirill09** [greenbits/brick#204]
Hi, is it possible to do a row query in brick? Perhaps there are other ways to solve the problem? Let me try to describe the problem using your example. You need to calculate which pizza is the most popular with customers? 
This is what the query should look like:
```
SELECT 
    Customer.* COUNT(*) 
FROM 
    Customer, _brick_Customer_pizzas 
WHERE 
    Customer._brick_id == _brick_Customer_pizzas.l_Customer_brick_id 
GROUP BY 
    _brick_Customer_pizzas.f_Pizza_brick_id
```
Thank you.

**Comment by tshedor** [comment]
Hey @kirill09 so Brick won't be able to do a fancy count like this through SQL but you could try this:

```dart
MyRepository().get<Customer>(query: Query(
  where: [
    Where.exact('pizzas', Where.exact('customer', Where('id').isExactly(id)))
  ]
));
```

This sort of nested query isn't ideal, but if you use the `@OfflineFirst(where:)` annotation, the adapter generates some magic SQL to make the connections work as soon as you hydrate from SQL.

**Comment by kirill09** [comment]
Hi, in this query you are counting the number of pizzas per user. I wanted to get a table:

```
CustomerId      COUNT(*)
    1             11
    2             42
    3             72
    4             14
    5             51
```

COUNT(*) = number of pizzas ordered by the customer.
In your query, I have to make this query for each customer

**Comment by tshedor** [comment]
@kirill09 brick won't have that output as it's concerned with outputting Models. If you want a `Map` like that I'd recommend using `SqliteProvider#rawQuery` at your own risk
