### ISSUE TITLE
GraphQL support?

### ISSUE THREAD

**Issue by chinitadelrey** [greenbits/brick#205]
This is an amazing library, thank you. From this [introduction video](https://www.youtube.com/watch?v=2noLcro9iIw) it seems that there is an intention to support graphQL. I tried looking in the docs and the various packages, but graphQL doesn't seem to be mentioned. Is it currently supported? If not, how might I and others be able to quickly put something together on our own end? I am using the [graphql_flutter library](https://zino-app.github.io/graphql-flutter/packages/graphql/) currently. 

Alternatively, if there are plans to support graphQL would be great for you to share with the community the timeline/roadmap for that? No pressure/worries. Thank you!

**Comment by tshedor** [comment]
Hi @chinitadelrey thanks for using Brick. 

That's an attentive catch to the video. While we were considering adding a GraphQL provider at the onset, I don't have the bandwidth to compose one in the near to intermediate future.

It would be fantastic if you wanted to lead an effort to make a GraphQL provider. I would recommend starting with the [Brick Build README](https://github.com/greenbits/brick/tree/master/packages/brick_build) to get a sense of nomenclature and how the other providers are architected. Then I would clone an established provider packages like [brick_rest_generators](https://github.com/greenbits/brick/tree/master/packages/brick_rest_generators) and change out the internals as you go. Depending on the input format from a GraphQL client, you may need to only tweak a few fields.

**Comment by chinitadelrey** [comment]
Thank you so much @tshedor for your very helpful guidance on how to proceed. 

Apologies for the delayed response. Right now I am getting by with one database table in my beta test. Have had to spend the past couple days on other issues on the backend. 

I will definitely seriously re-look into this at a later date especially when the app starts to scale up to more users. 

All the best in the meantime!
