### ISSUE TITLE
Support generics on types

### ISSUE THREAD

**Issue by porfirioribeiro** [greenbits/brick#31]
I want to add a type that has generic argument on my model.

```dart
  final Geometry<dynamic> geometry;
```

```
[SEVERE] brick_offline_first_with_rest_build:brickAdaptersBuilder on lib/app/models/field.dart:

Could not format because the source could not be parsed:

line 125, column 37: A comparison expression can't be an operand of another comparison expression.
    ╷
125 │             'type': Geometry<dynamic>,
    │                                     ^
    ╵
line 125, column 38: Expected an identifier.
    ╷
125 │             'type': Geometry<dynamic>,
    │                                      ^
    ╵
```

**Comment by tshedor** [comment]
@porfirioribeiro that's a fantastic edge case. How are you populating that type argument? Is it static, i.e. 

```dart
final Geometry<int> geometry;
```

or is it provided elsewhere? For example:

```dart
class Location<T> {
  final Geometry<T> geometry;
}
```

**Comment by porfirioribeiro** [comment]
It is actually `Geometry<dynamic>` 
I wan't to store a GeoJson, so i can use the `type` of the Geometry to parse/stringify it

Imagin this:
```dart
mixin FeatureLike {
  Geometry get geometry;
}

enum GeometryType { Polygon, MultiPolygon /*etc*/ }

abstract class Geometry<T> {
  GeometryType get type;
  T get coordinates;

  // this would be used on fromRest/fromSqlite
  static Geometry fromJson(Map<String, dynamic> json) {
    if (json['type'] == 'Polygon') return _$PolygonFromJson(json);
    if (json['type'] == 'MultiPolygon') return _$MultiPolygonFromJson(json);
    throw Exception('Invalid json');
  }
  // this would be used on toRest/toSqlite
  Map<String, dynamic> toJson() {
    if (this is Polygon) return _$PolygonToJson(this as Polygon);
    if (this is MultiPolygon) return _$MultiPolygonToJson(this as MultiPolygon);
    throw Exception('Unknown geometry subclass');
  }
}
class Polygon extends Geometry<List<List<List<double>>>> {
  @override
  final GeometryType type;

  @override
  final List<List<List<double>>> coordinates;

  Polygon({
    @required this.coordinates,
    this.type = GeometryType.Polygon,
  });
}
//....
```

What i am doing now is having `OfflineFirstSerdes` on `MultiPolygon` and the others, but that means i need to specify the exact GeoJson type. For the moment it's ok because i know my API only return's `MultiPolygons` 
```dart
final MultiPolygon geometry;
```
But i would like to specify the generic one:
```dart
final Geometry geometry;
```

**Comment by tshedor** [comment]
@porfirioribeiro after giving this some thought, 
1) The type argument must be passed to Geometry somehow, and that would require the deserializer to be aware of the argument. I'm going to leave this issue open for the time being because I want to remember to return to it, although it's not a high priority.
2) This specific error deals with the SQLite deserializer. So long as you're not serializing the types differently based on the type argument (which, by your description, you're not,  you're just changing properties), then using the type without the arguments shouldn't be an issue

Let me know if you disagree with any of that. I'll try to get a PR together soon.

**Comment by tshedor** [comment]
Hey @porfirioribeiro would you mind checking out [this branch](https://github.com/greenbits/brick/tree/strict-type-in-sqlite-mapping) and seeing if it will work for you?

**Comment by porfirioribeiro** [comment]
I'll get back to work at Wednesday, I'll try and report back to you.
Thanks

**Comment by porfirioribeiro** [comment]
Sorry for the delay, i just tested and it's working good on master!
