### ISSUE TITLE
Models in sub folders

### ISSUE THREAD

**Issue by porfirioribeiro** [greenbits/brick#38]
I would like to structure models using folders.
But putting models inside a folder do not work.
When you start getting many models might be hard to have them all in the same place

**Comment by tshedor** [comment]
Hey @porfirioribeiro  , at this time we're not going to support sub folders. The output of the builder has a very specific folder expectation. It's something that's on the roadmap, but is very unlikely to be addressed before an alpha release.

**Comment by tshedor** [comment]
Hey @porfirioribeiro I'm going to close this issue. This isn't a feature I intend to prioritize in the near future and it's been over a year since the issue was opened, so perhaps not in the long term either. 

However, PRs are always open for something like this and I'd welcome the code.
