### ISSUE TITLE
Store blob in database

### ISSUE THREAD

**Issue by porfirioribeiro** [greenbits/brick#39]
I have some models that returns base64 encoded images from REST and i want to store them on the database.
I can do it, storing it as a plain string, but it would be nice to convert it to `Uint8List` store it that way on the db but if i add:
```dart
Uint8List image;
```
To my model it stops being recognized by brick.

**Comment by tshedor** [comment]
@porfirioribeiro ah, yes. This will be tricky when converting the blob from SQLite back to Dart. 

Are there any other byte lists or formats that you can currently think of that would be stored as a blob?

**Comment by porfirioribeiro** [comment]
At this moment, only I only want to store images as blobs

In other parts of my app, out of brick i am also storing BLOBs with sfqlite and i can access the data easy in Dart

I would help on the implementation, but my knowledge of the brick code structure is still vague 🙄

**Comment by tshedor** [comment]
@porfirioribeiro I'm going to consolidate this issue to #42 and add a quick note for future readers of this ticket.

The author of SQFlite recommends avoiding the BLOB column type and instead storing the file/image and referencing the file path within SQLite: tekartik/sqflite#204

**Comment by porfirioribeiro** [comment]
In my case I'm storing a a small thumbnail on database to give a placeholder while the user clicks to get the full image.

It's not recommended not store big blobs on any database.
