### ISSUE TITLE
the example doesn't work

### ISSUE THREAD

**Issue by huntergps** [greenbits/brick#48]
Download, I followed the steps to run the example but it doesn't work correctly, it doesn't load the data from the local server

**Comment by tshedor** [comment]
@huntergps are you behind a firewall of any kind? Can you access `localhost:8080`?

**Comment by huntergps** [comment]
No, it is not behind a firewall, everything is locally.  The api server is running in localhost:8080.
I use mac with Mojave os. Any way to debug?

**Comment by huntergps** [comment]
Sorry it worked, it was my fault. The api server was not network enabled, only locally.

**Comment by tshedor** [comment]
Great to hear
