### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by huntergps** [greenbits/brick#50]
Where can I get a usage example, which allows reading data from an api rest server and doing CRUD operations?

**Comment by tshedor** [comment]
@huntergps have you checked out [the example package](https://github.com/greenbits/brick/blob/master/example/lib/main.dart) ?

**Comment by huntergps** [comment]
Of course, but it is too basic to understand how to use brick in a real app.

**Comment by tshedor** [comment]
@huntergps by definition, an example should be basic so that it's approachable.  

If you want to see an example of what's [available to models](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/example/lib/app/models/kitchen_sink.dart), the kitchen sink is a good example.
