### ISSUE TITLE
Add support for different platforms 

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#52]
Support for all platforms like in 
https://github.com/simolus3/moor/tree/master/moor_ffi

**Comment by tshedor** [comment]
@pkozlovskiy can you please provide more context? I'm unfamiliar with this package.

If you mean supporting sqlite3, Brick has a hard dependency on sqflite.

**Comment by pkozlovskiy** [comment]
> @pkozlovskiy can you please provide more context? I'm unfamiliar with this package.
> 
> If you mean supporting sqlite3, Brick has a hard dependency on sqflite.

But sqflite have ffi implementation
https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
wich supported on Linux, MacOS and Windows.
Maybe it is real change initialization of sqflite in brick like here
https://github.com/tekartik/sqflite/tree/master/sqflite_test_app/lib

**Comment by tshedor** [comment]
@pkozlovskiy Ah, that is fascinating. And great that sqflite supports it natively. Let me do a little experimenting and get back to you, but I think this is very achievable.

**Comment by tshedor** [comment]
Hey @pkozlovskiy [I've got a branch](https://github.com/greenbits/brick/tree/sqlite-ffi) for you to test run. Would you mind letting me know if it covers all your use cases? 

Example implementation:

```dart
import 'package:sqflite_common/sqlite_api.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

MyRepository(
  sqliteProvider: SqliteProvider(
    inMemoryDatabase,
    databaseFactory: databaseFactoryFfi,
  ),
);
```

You'll also want to [init the loader](https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi) before invoking:

```dart
void main() {
  sqfliteFfiInit();
  runApp(MyApp())
}
```
