### ISSUE TITLE
How to configure with Dio?

### ISSUE THREAD

**Issue by MilesAdamson** [greenbits/brick#53]
I am looking at trying to use this plugin with Dio as my api client. Currently, I have all the api working with Dio, and now want to do offline as the next step.

Just starting on this, haven't configured much of anything yet, but I think I ran into an issue where Dio is using [HttpClient](https://api.dart.dev/stable/2.8.1/dart-io/HttpClient-class.html) and your `RestProvider` expects a [Client](https://pub.dev/packages/http)

From the example project 

```
class Cache extends OfflineFirstWithRestRepository {
  Cache._(String baseUrl, Client client, String databaseName)
      : super(
          restProvider: RestProvider(
            baseUrl, client: client,
            modelDictionary: restModelDictionary,
          ),
          sqliteProvider: SqliteProvider(
            databaseName,
            modelDictionary: sqliteModelDictionary,
          ),
          memoryCacheProvider: MemoryCacheProvider(),
          migrations: migrations,
        );

  factory Cache() => _singleton ?? Exception("Must call configure first");

  static Cache _singleton;

  static void configure(String baseUrl, Client client, String databaseName) {
    _singleton = Cache._(
      baseUrl,
      client,
      databaseName,
    );
  }
}
```

```
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (client) {
      Cache.configure(dio.options.baseUrl, client, "database.db");
    };
```

![image](https://user-images.githubusercontent.com/29047682/81098724-02830b00-8ec7-11ea-97ea-c8be3a1eaa68.png)

So it appears as though I cannot give the api client in Dio to the `RestProvider`. Any ideas? Sorry if I'm missing something obvious

**Comment by tshedor** [comment]
@MilesAdamson so this is an interesting problem and it led me down a rabbit hole of dependencies. I'll summarize as best I can before getting to the solution:

1. Dio uses HttpClient which is from `dart:io:HttpClient`. Brick uses `HttpClient`, from `package:http/http.dart`
2. Really, all you need is a BaseClient to pass Dart's type checker. So I checked out `client.dart` (which has a useful note about the IOClient](https://github.com/dart-lang/http/blob/master/lib/src/client.dart#L33-L35). Previously I wasn't aware that there were two different http client implementations or that the http package didn't make its own clients, so uncharted territory here.
3. [According to the docs](https://github.com/dart-lang/http#using), composition should be used to take advantage of multiple http clients (commonly annotated as the "inner" client). The Offline Queue implements [this pattern to intercept and store requests](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/src/offline_queue/offline_queue_http_client.dart), for a fully fleshed out example. I can see that `IOClient` allows a composed inner client.

So, the solution, all said and done, is this (I think; untested code):

```dart
import 'package:http/io_client.dart';

(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
  (client) {
    final wrappedHttpClient = IOClient(client);
    Cache.configure(dio.options.baseUrl, wrappedHttpClient, "database.db");
  };
```

If this was useful, please comment back or submit a PR/Wiki documenting how you integrated Dio with Brick. I'm unfamiliar with dio but it seems to be a popular package and no doubt there's a large user base that would benefit.

**Comment by MilesAdamson** [comment]
I tried it out yesterday and it does compile and work, but it doesn't use the Dio level features I was hoping for. For example dio has connect timeouts and the headers already configured in the app but they aren't getting added and the on request hook isn't getting fired.

Thanks for looking into it! But I'm not sure if it's there much point in getting Dio's client referenced in you package. For my purposes it seems easiest to just configure the headers again with brick's plugin and let brick handle the api client.

```
    dio.options.baseUrl = 'https://${this.subDomain}.website.ca/api';
    dio.options.connectTimeout = 10000;
    dio.options.receiveTimeout = 30000;
    dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) async {
      // Do something before request is sent
      options.headers["Authorization"] = "Bearer $token";
```
