### ISSUE TITLE
Data in _$FromRest is missing keys which causes crash

### ISSUE THREAD

**Issue by MilesAdamson** [greenbits/brick#55]
Issue: some keys are missing in the data object when I reach the from rest method. The api I'm using returns complete objects within a job, opposed to only an id. These objects used to be created properly when using JsonSerializable:

```
    template: json['template'] == null
        ? null
        : Template.fromJson(json['template'] as Map<String, dynamic>),
    company: json['company'] == null
        ? null
        : Company.fromJson(json['company'] as Map<String, dynamic>),
```

Now when switching to brick offline, these object are missing completely from the data map. They aren't even null, the keys don't exist.

```
Future<Ticket> _$TicketFromRest(Map<String, dynamic> data,
    {RestProvider provider, OfflineFirstWithRestRepository repository}) async {
  print("company: ${data.containsKey("company")}");
  print("template: ${data.containsKey("template")}");
```

```
I/flutter (29717): company: false
I/flutter (29717): template: false
E/flutter (29717): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (29717): Receiver: null
E/flutter (29717): Tried calling: []("id")
E/flutter (29717): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (29717): #1      _$CompanyFromJson (package:my_app/app/models/company.g.dart:11:13)
```

This causes a crash whenever `_$TicketFromRest` is called, because it attempts to calls `TemplateAdapter().fromRest(data['template'],` and `data['template']` is null.

Sanity check: it 100% exists on the payload the app receives:

![image](https://user-images.githubusercontent.com/29047682/81591555-d6a9ce80-9379-11ea-86a9-9017952d1310.png)

**Comment by tshedor** [comment]
@MilesAdamson in your `Ticket.dart` model, how are you accessing `Template` or `Company`? 

Ideally, they would look like this:

```dart
class Ticket extends OfflineFirstWithRestModel {
  final Template template;
  final Company company;
}
```

If `Template` and `Company`  are models in their own right, Brick should generate a `Template.fromRest`. But if they're not declared at all, they won't appear in the adapter

**Comment by MilesAdamson** [comment]
I'm not sure if it had something to do with the class hierarchy I had, but I have since fixed this issue by deleting the `TicketStub` class and just letting company and template be null if the ticket is a "stub".

Template and Company are both `Identifiable`, and both had adapters created properly. Issue was, in the `_$TicketFromRest` method `data` was missing them. But with just `Ticket extends Identifiable` it's now working, not sure why

```
class Ticket extends TicketStub {
  final Company company;
  final Template template;
  
```

```
class TicketStub extends Identifiable {
  final int id;
  // many other things...
```

```
abstract class Identifiable extends OfflineFirstWithRestModel implements Comparable {
  final dynamic id;
```

**Comment by tshedor** [comment]
Interesting...there must be something in the way analyzer detects the class. There must be a way to keep going further up the tree and detect if `OfflineFirstWithRestModel` is a super at _any_ point. I'll do some digging.

**Comment by tshedor** [comment]
@MilesAdamson can you please give https://github.com/greenbits/brick/pull/67 a test? I think that should fix this.
