### ISSUE TITLE
Crash on upsert with nullable object

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#58]
I have field in my model
@Rest(nullable: true)
final Attachment logoAttachment;

When trying upsert with null value get error:
Unhandled Exception: Unhandled error type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Attachment'
In _$SoemThingToRest in adapter on line

'logoAttachment':
        await AttachmentAdapter().toRest(instance.logoAttachment ?? {}),

**Comment by tshedor** [comment]
@pkozlovskiy that doesn't look like a null value, it looks like a serializer error. This is a very silly Brick bug in the generators. Let me get a quick fix together.
