### ISSUE TITLE
Is there any way to tell why I got an empty array from a get?

### ISSUE THREAD

**Issue by MilesAdamson** [greenbits/brick#60]
Issue: when I'm loading a list of jobs with `requireRemote = true`, I get an empty list of jobs when any error happens at all. An empty list of jobs due to no work to be done and an empty list because there was an http error is very different. 

I would like to be able to catch http errors or at least receive `null` to know something went wrong. Is this possible?

**Comment by tshedor** [comment]
@MilesAdamson is your API returning a 200-level status code when you get an empty list of jobs? Is "any error happens at all" in reference to the error occurring on the client or the API?

**Comment by MilesAdamson** [comment]
Yes, the api returns 200 ok for an empty list of jobs. The issue is, it seems like most errors will result in this as well.

- 400 bad request when doing the api call
- no response from server at all
- 500 server error

Take this code for example:

```Stream<JobsState> loadList(JobsLoadList event) async* {
  yield JobsLoading();
  try {
    List<Job> jobs = await EnvironmentBloc.getInstance().repository.get<Job>(
        requireRemote: true,
        query: Query(
          action: QueryAction.get,
          where: [
            // Purposely malform start time to get 400 bad request
            Or("startTime")
                .isLessThan(event.endIsoString.replaceRange(3, 4, ".^")),
            Or("endTime").isLessThan(event.endIsoString)
          ],
        ));

    yield JobsLoaded(jobs: jobs.toList());
  } catch (e) {
    yield JobsError(message: DioHelper.messageFromError(e));
  }
}

Before switching to brick from a normal api call, a 400 bad request would throw an error. This would be caught by the bloc and an error state would happen, letting the user know. Now, with brick, there is no error thrown and instead it appears as though there are no jobs.

I can even make the URL complete nonsense, and instead of getting errors, I get empty lists:

```
          restProvider: RestProvider(
            "https://qwertrgwefqyuiop.ca/api/v2",
            modelDictionary: restModelDictionary,
          ),
```

**Comment by tshedor** [comment]
@MilesAdamson does removing the extra `toList()` in `jobs.toList()` resolve your empty list issue? Is `400` in your [reattemptForStatusCodes](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/offline_first_with_rest.dart#L69)? The request may be being swallowed and reattempted in the background.

Regarding your issue for "I can even make the URL complete nonsense," have you configured [your repository to throw on 404s](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/lib/offline_first_with_rest.dart#L50-L56)?

**Comment by MilesAdamson** [comment]
I have not edited `reattemptForStatusCodes`. I did not configure the repository to throw for 404's, however it would be good to do so. This causes loading by id to throw as I would want, but still a nonsense URL or internal server error yields me an empty list of jobs

![image](https://user-images.githubusercontent.com/29047682/82950670-ecff7f00-9f62-11ea-827c-f3156048bf20.png)

**Comment by tshedor** [comment]
@MilesAdamson does removing the extra toList() in jobs.toList() resolve your empty list issue?

**Comment by MilesAdamson** [comment]
Unfortunately, it does not. I still get an empty list from brick

![image](https://user-images.githubusercontent.com/29047682/82953037-51bcd880-9f67-11ea-8bda-165eea976abb.png)

![image](https://user-images.githubusercontent.com/29047682/82953045-541f3280-9f67-11ea-9158-cf7c90f80201.png)

**Comment by tshedor** [comment]
@MilesAdamson thanks for your patience debugging. I wanted to exhaust the obvious culprits before diving in.

In the `SqliteProvider` source, when no models are found, [an empty list is returned](https://github.com/greenbits/brick/blob/master/packages/brick_sqlite/lib/sqlite.dart#L215-L218). IIRC, this is to reduce the nullability checks in subsequent operations. Since `requireRemote` only guarantees that REST will hydrate the local SQLite instance before returning results instead of directly returning the results from REST (otherwise it wouldn't be `OfflineFirst`, it would be `OfflineFirstOnlyForDefaultOptions`), no results is equivalent to an empty results list.

**Comment by MilesAdamson** [comment]
No worries, thanks for the plugin haha. It is working very well still. 

Ok, that's interesting. What happens in my case is I have a list of jobs. If that request fails, instead of seeing the jobs which they already had loaded, they see nothing. So, the workaround for now is if I get an empty list from a get, I just yield with that already in state.

Not crazy about it but it does seem to do the trick

```
    if (jobsFromServer.isNotEmpty) {
      yield JobsLoaded(jobs: jobsFromServer.toList());
    } else {
      yield JobsLoaded(jobs: jobs);
    }
```

**Comment by tshedor** [comment]
This is getting into application code now, but you could also add a `copyWith` method to `JobsLoaded`:

```dart
class JobsLoaded extends State {
  JobsLoaded({this.jobs});

  JobsLoaded copyWith({
    List<Job> jobs
  }) {
    return JobsLoaded(
      jobs: jobs.isNotEmpty ? jobs : this.jobs
    );
  }
}
```

**Comment by tshedor** [comment]
@MilesAdamson going to close this out but please open a new issue if the above code doesn't work for you.

**Comment by hortigado** [comment]
Hi, is there a way to change this? Getting an empty list when there's no internet connection, for example, is unsafe because I don't know if the document is actually missing from the server or if it was just an error.

For example, sometimes I want to know if a user has already been created, but sometimes when the user doesn't have internet access, it returns an empty list, which causes me to run a function to create the user again, even though the user already exists in the database.
