### ISSUE TITLE
Relationships 

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#65]
If I have two models
class Project extends OfflineFirstWithRestModel {
  @Sqlite(unique: true)
  final String id;
...

class Job extends OfflineFirstWithRestModel {
  @Sqlite(unique: true)
  final String id;
  final String projectId;
...
What is the best way to get 

class ProjectWithJobs {
  final Project project;
  final List<Job> jobs;

  ProjectWithJobs(this.project, this.jobs);
}

for presentation layer?

**Comment by tshedor** [comment]
Hey @pkozlovskiy I think the best way to do that would be to access one model instead of doing a joins.

```dart
class Project extends OfflineFirstWithRestModel {
  @sqlite(unique: true)
  final String id;
  
  @OfflineFirstWhere('id': "data['job_ids']"})
  @Rest(name: 'job_ids')
  final List<Job> jobs;
}
```

This assumes that your Project REST response resembles this: 

```json
{
  "job_ids": ["1", "2", "3"]
}
```

And that your `/jobs` endpoint has member access (i.e. `jobs/1`, `jobs/2`)

**Comment by pkozlovskiy** [comment]
> Hey @pkozlovskiy I think the best way to do that would be to access one model instead of doing a joins.
> 
> ```dart
> class Project extends OfflineFirstWithRestModel {
>   @sqlite(unique: true)
>   final String id;
>   
>   @OfflineFirstWhere('id': "data['job_ids']"})
>   @Rest(name: 'job_ids')
>   final List<Job> jobs;
> }
> ```
> 
> This assumes that your Project REST response resembles this:
> 
> ```json
> {
>   "job_ids": ["1", "2", "3"]
> }
> ```
> 
> And that your `/jobs` endpoint has member access (i.e. `jobs/1`, `jobs/2`)

This is nice way in many situation, but if I can't change backend api, and it can't send me job_ids in /projects

**Comment by pkozlovskiy** [comment]
> @pkozlovskiy ah, ok, in that case, I would do something like this:
> 
> ```dart
> @ConnectOfflineFirst(
>   restConfig: RestSerializable(
>     endpoint: r'''{
>       if (query?.action == QueryAction.get && query.where != null) {
>           final searchByProject = Where.firstByField('project', query.where);
>           if (searchByProject?.value != null) {
>             return "/jobs?project_id=${searchByProject.value.id}";
>           }
>       }
>       // ....rest of your endpoint code.....
>     }'''
>   )
> )
> class Job extends OfflineFirstWithRestModel {
>   @OfflineFirst(where: {'id': 'data["project_id"]'})
>   @Rest(name: 'project_id')
>   final Project project;
> }
> ```
> 
> Which would be invoked like this:
> 
> ```dart
> final Project project = // TODO
> final jobs = await MyRepository().get<Job>(query: Query.where('project', Where('id').isExactly(project.id));
> ```

Thanks, I try to use this case!
