### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by Jeremywhiteley** [greenbits/brick#68]
Any plans to support Flutter web?   Perhaps using sql-wasm.js as in this code example?    

https://github.com/rodydavis/moor_shared/tree/master/web

**Comment by tshedor** [comment]
Hey @Jeremywhiteley there aren't current plans to support SQLite on the web until there's a suitable solution in [sqflite, which has a long running thread about this](https://github.com/tekartik/sqflite/issues/212). However, there looks like some very recent experimental work being done on [this repo](https://github.com/deakjahn/sqflite_web). If you want to give that a go, you just need to define the database factory:

```yaml
dependencies:
  universal_platform: ^0.1.3
  sqflite_web:
    git:
      path: git@github.com:deakjahn/sqflite_web.git
```

And then in your Repository (**untested code**):

```dart  
import 'package:sqflite_common/sqlite_api.dart';
import 'package:sqflite_web/sqflite_web.dart';
import 'package:universal_platform/universal_platform.dart'; // necessary for persistence to disk on Android/iOS

import 'brick.g.dart'; // of course, relative to your repository

MyOfflineFirstRepository(
  sqliteProvider: SqliteProvider(
    UniversalPlatform.isWeb ? inMemoryDatabasePath : 'my_custom_database.sqlite',
    databaseFactory: UniversalPlatform.isWeb ? databaseFactoryWeb : null,
    modelDictionary: sqliteModelDictionary,
  )
)
```

I haven't read that discussion too closely, but there's a fair chance that your DB won't be persisted between sessions or tabs on the web. I'd also recommend giving feedback as you uncover bugs to that sqflite_web repo.

**Comment by rodydavis** [comment]
Just wanted to though this out there and curious if it was considered.

https://github.com/simolus3/drift/issues/2382

Chrome is also remove WebSQL in favor of SQLite on the web:

https://developer.chrome.com/blog/sqlite-wasm-in-the-browser-backed-by-the-origin-private-file-system/
