### ISSUE TITLE
Can Brick Sync Data from SQLProvider to RestProvider?

### ISSUE THREAD

**Issue by papakay** [greenbits/brick#84]

**Comment by tshedor** [comment]
@papakay yes. When you run `MyRepository().upsert<Model>(modelInstance)`  (given `MyRepository extends OfflineFirstWithRestRepository`) the `modelInstance` is synced with both your local SQLite and your REST endpoint.

If you're offline when that method is invoked, the transmitted data is cached and reattempted until it receives a response from the RestProvider.

**Comment by papakay** [comment]
This is super awesome! I'm so glad to hear this. Thank you a lot @tshedor
