### ISSUE TITLE
Can't build the app

### ISSUE THREAD

**Issue by polRk** [greenbits/brick#86]
```
[WARNING] No actions completed for 15.0s, waiting on:
  - brick_offline_first_with_rest_build:brickAdaptersBuilder on lib/app/models/user_dto.dart
  - brick_offline_first_with_rest_build:brickAdaptersBuilder on lib/app/models/task_dto.dart

[INFO] 1h 56m elapsed, 1/3 actions completed.
```

**Comment by tshedor** [comment]
Hi @polRk this looks like you're not building the example app. From this snippet, there are no errors. Are you able to share any additional code or log messaging, such as the point of crash when you run `flutter build`? 

And assuming `dto` stands for "data transfer object," Brick builds data transfer objects automatically as adapters. Your models should represent data in its end state.

**Comment by tshedor** [comment]
@polRk if you're using Flutter >1.20, there are a number of `build_runner` [issues floating](https://github.com/flutter/flutter/issues/63556) around. For example, [hive](https://github.com/hivedb/hive/issues/387#issuecomment-663900752), [json_serializable](https://github.com/flutter/flutter/issues/62240), and [flutter](https://github.com/flutter/flutter/issues/62996).

For the time being, I would recommend adding this to your `pubspec.yaml` as this has worked for me to get the example to compile:

```yaml
dev_dependencies:
  build_runner: '>= 1.10.1'

dependency_overrides:
  analyzer: 0.39.14
```

**Comment by polRk** [comment]
Thank you! It's work!

**Comment by tshedor** [comment]
@polRk if you encounter a similar build issue in 1.22, try removing the hard dependency on `analyzer` and running `flutter pub upgrade`
