### ISSUE TITLE
Expected an identifier after flutter upgrade

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#87]
Get 
flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] brick_offline_first_with_rest_build:brickAdaptersBuilder on 

After flutter upgrade

[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/pako/flutter
    • Framework revision bbfbf1770c (16 hours ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

**Comment by tshedor** [comment]
@pkozlovskiy can you try the resolution steps here: https://github.com/greenbits/brick/issues/86 ?

**Comment by pkozlovskiy** [comment]
> @pkozlovskiy can you try the resolution steps here: #86 ?

Thanks, it helps

**Comment by tshedor** [comment]
@pkozlovskiy if you encounter a similar build issue in 1.22, try removing the hard dependency on `analyzer` and running `flutter pub upgrade`
