### ISSUE TITLE
How to properly change associated data

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#89]
I use associations like in example
  @OfflineFirst(where: {'id': "data['pizza_ids']"})
  @Rest(name: 'pizza_ids')
  final List<Pizza> pizzas;

First I upsert Customer with some pizzas, and then I want to change his list of pizzas, I try to upsert this Customer with new list of pizzas, but when I fetch this customer after that it has ALL pizzas from first and second lists, but I expect only second.

**Comment by tshedor** [comment]
@pkozlovskiy how are you mutating the list of pizzas? I would recommend an immutable approach:

```dart

final pizzas = [pizza1];
final customer = Customer(pizzas: pizzas, uniqueIdentifier: 2);
final newPizzas = List<Pizza>.from(customer.pizzas);
newPizzas.add(Pizza());
final customerWithNewPizzas = Customer(pizzas: newPizzas, uniqueIdentifier: customer.uniqueIdentifier); // or something like customer.copyWith(pizzas: newPIzzas)
await Repository().upsert<Customer>(customerWithNewPizzas);
```
